# Generated by Django 4.2.1 on 2023-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='active_books',
            field=models.ManyToManyField(blank=True, to='core.book', verbose_name='Взятые книги'),
        ),
    ]
