# Generated by Django 4.2.1 on 2023-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reader_active_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='author_fotos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='active_books',
            field=models.ManyToManyField(max_length=3, to='core.book'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_active',
            field=models.CharField(choices=[('активен', 'Is Active'), ('не активен', 'Not Active')], default='активен', max_length=10, verbose_name='Активен'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'surname')},
        ),
    ]
